### ISSUE TITLE
Set bushes, vases and stones' ground as "low wall"

### ISSUE THREAD

**Issue by princededede** [team-zhsa/zelda-hsa#158]
bug au niveau de la maison à gauche de la maison à gauche des gardes de la ville d'hyrule

**Comment by team-zhsa** [comment]
il se passe quoi exactement ? peux tu me décrire le bug ?

**Comment by team-zhsa** [comment]
Working as intended

**Comment by team-zhsa** [comment]
Was "Fix the vases not being thrown over other vases"

**Comment by team-zhsa** [comment]
See https://gitlab.com/solarus-games/solarus/-/issues/1045
